book/urls.py
from django.urls import path
from book import views

urlpatterns = [
    path('get_data/', views.get_books_by_emag, name='get-data')
]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from userextend.forms import AuthenticationNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('trainer.urls')),
    path('login/', views.LoginView.as_view(form_class=AuthenticationNewForm), name='login'),
    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),
    path('', include('book.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/models.py
from django.db import models

from trainer.models import Trainer


class Student(models.Model):
    gender_options = (('male', 'Male'), ('female', 'Female'))

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    email = models.EmailField(max_length=50)
    description = models.TextField(max_length=500)
    start_date = models.DateField()
    end_date = models.DateField()
    active = models.BooleanField(default=True)
    gender = models.CharField(max_length=6, choices=gender_options)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # auto_not_add=True-> va stoca data si ora in momentul in care voi salva studentul in tabela.
    # NU SE MAI POATE SCHIMBA DATA SI ORA
    # auto_now = True ->va stoca data si ora in momentul salvarii. Data si ora va fi actualizata de
    # fiecare data cand realizez ca modifcari asupra studentului

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

trainer/models.py
from django.db import models

# Create your models here.


class Trainer(models.Model):
    department_options = (('backend', 'Backend'), ('frontend', 'Frontend'), ('network', 'Network'))

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    course = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    department = models.CharField(max_length=10, choices=department_options)
    active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='img/', null=True)
    file = models.FileField(upload_to='file/', null=True)

    hours = models.IntegerField(null=True)
    price = models.IntegerField(null=True)
    total = models.IntegerField(null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
</body>
</html>

templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .edit_h3 {
            color: red;
        }
    </style>
</head>
<body>
<h3 class="edit_h3">Hello, {{ fullname }}</h3>
<p>Your username is: {{ username }}</p>
<a href="{{ url }}">Activate</a>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Django Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Intro
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'list-of-cars' %}">List of cars</a></li>
                        <li><a class="dropdown-item" href="{% url 'list-of-series' %}">List of series</a></li>
                    </ul>
                </li>
                {% if perms.student.add_student or perms.student.view_list_of_students %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Student
                        </a>
                        <ul class="dropdown-menu">
                            {% if perms.student.add_student %}
                                <li><a class="dropdown-item" href="{% url 'create_student' %}">Create a new student</a>
                                </li>
                            {% endif %}
                            {% if perms.student.view_list_of_students %}
                                <li><a class="dropdown-item" href="{% url 'list_of_students' %}">List of students</a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                {% endif %}

                {% if perms.trainer.add_trainer or perms.trainer.view_list_of_trainers %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Trainer
                        </a>
                        <ul class="dropdown-menu">
                            {% if perms.trainer.add_trainer %}
                                <li><a class="dropdown-item" href="{% url 'create-trainer' %}">Create a new trainer</a>
                                </li>
                            {% endif %}
                            {% if perms.trainer.view_list_of_trainers %}
                                <li><a class="dropdown-item" href="{% url 'list-of-trainers' %}">List of trainers </a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle " href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            List of students
                        </a>
                        <ul class="dropdown-menu">
                            {% for student in students %}
                                <li><a class="dropdown-item"
                                       href={% url 'details_student' student.id %}>{{ student.first_name }} {{ student.last_name }}</a>
                                </li>
                            {% endfor %}

                        </ul>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'get-data' %}">Add books by Emag</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        My profile, {{ user.username }}
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </div>
                <form method="get" class="d-flex" role="search" action="{% url 'search' %}">
                    <input class="form-control me-2" type="search" name="search" placeholder="Search"
                           aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            {% else %}
                <div>
                    <a href="{% url 'login' %}" class="btn btn-outline-dark">Log in</a>
                    <a href="{% url 'create_user' %}" class="btn btn-outline-success">Sign up</a>
                </div>
            {% endif %}
        </div>
    </div>
</nav>